export function getStyles(colors, isDark) {
  const surface = isDark ? "rgba(15, 23, 32, 0.88)" : "rgba(255, 255, 255, 0.82)";
  const surfaceAlt = isDark ? "rgba(19, 28, 39, 0.92)" : "#f8fafc";
  const border = isDark ? "rgba(148, 163, 184, 0.16)" : "rgba(148, 163, 184, 0.28)";
  const mutedHeader = isDark ? "rgba(148, 163, 184, 0.12)" : "#e2e8f0";

  return {
    summaryBar: {
      display: "grid",
      gridTemplateColumns: { xs: "1fr", md: "repeat(3, minmax(0, 1fr))" },
      gap: "12px",
      mb: "18px",
    },
    summaryItem: {
      display: "flex",
      alignItems: "center",
      gap: "14px",
      px: "18px",
      py: "16px",
      borderRadius: "18px",
      background: surface,
      border: `1px solid ${border}`,
      boxShadow: isDark ? "0 18px 34px rgba(2, 6, 23, 0.28)" : "0 16px 32px rgba(148, 163, 184, 0.18)",
      backdropFilter: "blur(14px)",
    },
    summaryIconWrap: {
      width: 42,
      height: 42,
      borderRadius: "14px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(45, 212, 191, 0.10)" : "rgba(15, 118, 110, 0.08)",
      border: `1px solid ${isDark ? "rgba(45, 212, 191, 0.18)" : "rgba(15, 118, 110, 0.14)"}`,
    },
    summaryIcon: {
      color: colors.greenAccent[400],
      fontSize: 20,
    },
    summaryLabel: {
      fontSize: "0.78rem",
      letterSpacing: "0.04em",
      textTransform: "uppercase",
      color: colors.grey[400],
      mb: "4px",
    },
    summaryValue: {
      fontSize: "1.5rem",
      lineHeight: 1,
      fontWeight: 800,
      color: colors.grey[100],
    },
    toolbarShell: {
      mb: "18px",
      px: { xs: "14px", md: "18px" },
      py: { xs: "14px", md: "16px" },
      borderRadius: "18px",
      background: surface,
      border: `1px solid ${border}`,
      display: "flex",
      alignItems: { xs: "stretch", md: "center" },
      justifyContent: "space-between",
      gap: "14px",
      flexDirection: { xs: "column", md: "row" },
      boxShadow: isDark ? "0 16px 30px rgba(2, 6, 23, 0.24)" : "0 14px 28px rgba(148, 163, 184, 0.16)",
    },
    toolbarGroup: {
      display: "flex",
      alignItems: { xs: "stretch", sm: "center" },
      gap: "12px",
      flexDirection: { xs: "column", sm: "row" },
    },
    toolbarLabel: {
      fontSize: "0.82rem",
      fontWeight: 700,
      color: colors.grey[300],
      whiteSpace: "nowrap",
    },
    selectControl: {
      minWidth: 210,
      "& .MuiOutlinedInput-root": {
        borderRadius: "12px",
        backgroundColor: surfaceAlt,
      },
    },
    searchField: {
      width: { xs: "100%", md: 320 },
      ml: { md: "auto" },
      "& .MuiOutlinedInput-root": {
        borderRadius: "12px",
        backgroundColor: surfaceAlt,
      },
    },
    panelShell: {
      borderRadius: "22px",
      background: surface,
      border: `1px solid ${border}`,
      boxShadow: isDark ? "0 18px 34px rgba(2, 6, 23, 0.32)" : "0 16px 34px rgba(148, 163, 184, 0.18)",
      overflow: "hidden",
    },
    panelHeader: {
      px: { xs: "16px", md: "22px" },
      py: { xs: "16px", md: "20px" },
      borderBottom: `1px solid ${border}`,
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: "12px",
    },
    panelTitle: {
      fontSize: "1.08rem",
      fontWeight: 800,
      color: colors.grey[100],
    },
    panelSubtitle: {
      mt: "4px",
      fontSize: "0.86rem",
      color: colors.grey[400],
    },
    panelTitleIconWrap: {
      width: 38,
      height: 38,
      borderRadius: "14px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(45, 212, 191, 0.10)" : "rgba(13, 148, 136, 0.08)",
      border: `1px solid ${isDark ? "rgba(45, 212, 191, 0.16)" : "rgba(13, 148, 136, 0.14)"}`,
    },
    listBody: {
      px: { xs: "16px", md: "22px" },
      py: "18px",
      display: "flex",
      flexDirection: "column",
      gap: "10px",
    },
    historyRowShell: {
      borderRadius: "18px",
      border: `1px solid ${border}`,
      backgroundColor: surfaceAlt,
      overflow: "hidden",
    },
    historyRowHeader: {
      display: "flex",
      alignItems: "center",
      gap: "14px",
      p: "16px",
      cursor: "pointer",
      transition: "background-color 0.2s ease",
      "&:hover": {
        backgroundColor: isDark ? "rgba(30, 41, 59, 0.72)" : "rgba(241, 245, 249, 0.92)",
      },
    },
    avatarBadge: {
      width: 42,
      height: 42,
      borderRadius: "14px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "#f8fafc",
      fontWeight: 800,
      fontSize: "1rem",
      flexShrink: 0,
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.22)",
    },
    studentName: {
      fontSize: "1rem",
      fontWeight: 800,
      color: colors.grey[100],
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    studentMeta: {
      mt: "4px",
      fontSize: "0.82rem",
      color: colors.grey[400],
    },
    historyActions: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      marginLeft: "auto",
      flexShrink: 0,
    },
    countPill: (count) => ({
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      minWidth: 116,
      px: "12px",
      py: "7px",
      borderRadius: "999px",
      fontSize: "0.78rem",
      fontWeight: 700,
      color: count > 0 ? colors.grey[200] : colors.grey[400],
      backgroundColor: mutedHeader,
      border: `1px solid ${border}`,
    }),
    expandedPanel: {
      p: "16px",
      borderTop: `1px solid ${border}`,
      backgroundColor: isDark ? "rgba(15, 23, 32, 0.78)" : "rgba(248, 250, 252, 0.92)",
    },
    resultBlock: {
      p: "14px 16px",
      borderRadius: "14px",
      backgroundColor: isDark ? "rgba(19, 28, 39, 0.9)" : "rgba(255, 255, 255, 0.98)",
      border: `1px solid ${border}`,
      minWidth: 0,
    },
    resultBlockLabel: {
      fontSize: "0.74rem",
      fontWeight: 800,
      textTransform: "uppercase",
      letterSpacing: "0.05em",
      color: colors.grey[400],
      mb: "8px",
    },
    resultBlockText: {
      fontSize: "0.9rem",
      lineHeight: 1.6,
      color: colors.grey[200],
      whiteSpace: "pre-wrap",
    },
    paginationRow: {
      px: { xs: "16px", md: "22px" },
      pt: 0,
      pb: { xs: "18px", md: "22px" },
      display: "flex",
      justifyContent: "space-between",
      alignItems: { xs: "flex-start", md: "center" },
      gap: "12px",
      flexDirection: { xs: "column", md: "row" },
    },
    pagination: {
      "& .MuiPaginationItem-root": {
        color: colors.grey[100],
        borderColor: border,
        "&.Mui-selected": {
          backgroundColor: isDark ? "rgba(13, 148, 136, 0.28)" : "rgba(13, 148, 136, 0.18)",
          color: colors.grey[100],
          fontWeight: 800,
        },
        "&:hover": {
          backgroundColor: mutedHeader,
        },
      },
    },
    paginationText: {
      fontSize: "0.82rem",
      color: colors.grey[400],
    },
    loadingState: {
      minHeight: 240,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "12px",
      px: "20px",
    },
    loadingText: {
      color: colors.grey[300],
    },
    emptyState: {
      minHeight: 260,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "10px",
      px: "20px",
      textAlign: "center",
    },
    emptyStateIconWrap: {
      width: 52,
      height: 52,
      borderRadius: "18px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(45, 212, 191, 0.10)" : "rgba(13, 148, 136, 0.08)",
    },
    emptyStateTitle: {
      fontSize: "1rem",
      fontWeight: 800,
      color: colors.grey[100],
    },
    emptyStateText: {
      fontSize: "0.88rem",
      color: colors.grey[400],
      maxWidth: 420,
    },
  };
}
