export function getStyles(colors, isDark) {
  const surface = isDark ? "rgba(15, 23, 32, 0.88)" : "rgba(255, 255, 255, 0.82)";
  const surfaceAlt = isDark ? "rgba(19, 28, 39, 0.92)" : "#f8fafc";
  const border = isDark ? "rgba(148, 163, 184, 0.16)" : "rgba(148, 163, 184, 0.28)";
  const mutedHeader = isDark ? "rgba(148, 163, 184, 0.12)" : "#e2e8f0";

  return {
    summaryBar: {
      display: "grid",
      gridTemplateColumns: { xs: "1fr", md: "repeat(3, minmax(0, 1fr))" },
      gap: "12px",
      mb: "18px",
    },
    summaryItem: {
      display: "flex",
      alignItems: "center",
      gap: "14px",
      px: "18px",
      py: "16px",
      borderRadius: "18px",
      background: surface,
      border: `1px solid ${border}`,
      boxShadow: isDark ? "0 18px 34px rgba(2, 6, 23, 0.28)" : "0 16px 32px rgba(148, 163, 184, 0.18)",
      backdropFilter: "blur(14px)",
    },
    summaryIconWrap: {
      width: 42,
      height: 42,
      borderRadius: "14px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(45, 212, 191, 0.10)" : "rgba(15, 118, 110, 0.08)",
      border: `1px solid ${isDark ? "rgba(45, 212, 191, 0.18)" : "rgba(15, 118, 110, 0.14)"}`,
    },
    summaryIcon: {
      color: colors.greenAccent[400],
      fontSize: 20,
    },
    summaryLabel: {
      fontSize: "0.78rem",
      letterSpacing: "0.04em",
      textTransform: "uppercase",
      color: colors.grey[400],
      mb: "4px",
    },
    summaryValue: {
      fontSize: "1.5rem",
      lineHeight: 1,
      fontWeight: 800,
      color: colors.grey[100],
    },
    toolbarShell: {
      mb: "18px",
      px: { xs: "14px", md: "18px" },
      py: { xs: "14px", md: "16px" },
      borderRadius: "18px",
      background: surface,
      border: `1px solid ${border}`,
      display: "flex",
      alignItems: { xs: "stretch", md: "center" },
      justifyContent: "space-between",
      gap: "14px",
      flexDirection: { xs: "column", md: "row" },
      boxShadow: isDark ? "0 16px 30px rgba(2, 6, 23, 0.24)" : "0 14px 28px rgba(148, 163, 184, 0.16)",
    },
    toolbarGroup: {
      display: "flex",
      alignItems: { xs: "stretch", sm: "center" },
      gap: "12px",
      flexDirection: { xs: "column", sm: "row" },
    },
    toolbarLabel: {
      fontSize: "0.82rem",
      fontWeight: 700,
      color: colors.grey[300],
      whiteSpace: "nowrap",
    },
    selectControl: {
      minWidth: 210,
      "& .MuiOutlinedInput-root": {
        borderRadius: "12px",
        backgroundColor: surfaceAlt,
      },
    },
    searchField: {
      width: { xs: "100%", md: 320 },
      ml: { md: "auto" },
      "& .MuiOutlinedInput-root": {
        borderRadius: "12px",
        backgroundColor: surfaceAlt,
      },
    },
    aiDisabledBanner: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      p: "14px 18px",
      backgroundColor: isDark ? "rgba(220, 38, 38, 0.12)" : "rgba(239, 68, 68, 0.08)",
      borderBottom: `1px solid ${isDark ? "rgba(220, 38, 38, 0.2)" : "rgba(239, 68, 68, 0.15)"}`,
    },
    aiDisabledText: {
      fontSize: "0.86rem",
      color: isDark ? colors.redAccent[200] : colors.redAccent[600],
    },
    aiResultsGrid: {
      display: "grid",
      gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" },
      gap: "16px",
      mb: "16px",
    },
    aiResultCard: {
      backgroundColor: isDark ? "rgba(19, 28, 39, 0.82)" : "#ffffff",
      borderRadius: "16px",
      p: "18px",
      border: `1px solid ${border}`,
    },
    aiResultName: {
      fontSize: "1rem",
      fontWeight: 800,
      color: colors.grey[100],
    },
    aiResultClass: {
      fontSize: "0.82rem",
      color: colors.grey[400],
    },
    aiClassChip: {
      backgroundColor: mutedHeader,
      color: colors.grey[200],
      fontWeight: 600,
      borderRadius: "10px",
    },
    aiTextBlock: {
      mt: "14px",
    },
    aiBlockLabel: {
      fontSize: "0.76rem",
      textTransform: "uppercase",
      letterSpacing: "0.04em",
      fontWeight: 800,
      color: colors.greenAccent[400],
      mb: "6px",
    },
    aiBlockText: {
      fontSize: "0.88rem",
      lineHeight: 1.6,
      color: colors.grey[200],
    },
    aiErrorCard: {
      p: "20px",
      backgroundColor: isDark ? "rgba(220, 38, 38, 0.12)" : "rgba(239, 68, 68, 0.08)",
      borderRadius: "16px",
      border: `1px solid ${isDark ? "rgba(220, 38, 38, 0.2)" : "rgba(239, 68, 68, 0.15)"}`,
      textAlign: "center",
      maxWidth: 600,
      mx: "auto",
    },
    aiErrorText: {
      color: isDark ? colors.redAccent[200] : colors.redAccent[600],
      fontWeight: 700,
      mb: "10px",
    },
    aiRawText: {
      display: "block",
      textAlign: "left",
      p: "12px",
      backgroundColor: isDark ? "rgba(0,0,0,0.2)" : "rgba(255,255,255,0.6)",
      borderRadius: "8px",
      whiteSpace: "pre-wrap",
      color: colors.grey[300],
      fontSize: "0.75rem",
      fontFamily: "monospace",
    },
    aiRemarksCard: {
      p: "20px",
      backgroundColor: isDark ? "rgba(10, 15, 23, 0.6)" : "rgba(240, 244, 248, 0.8)",
      borderRadius: "16px",
      border: `1px solid ${border}`,
    },
    aiRemarksTitle: {
      fontSize: "0.9rem",
      fontWeight: 800,
      color: colors.grey[200],
      mb: "12px",
    },
    aiRemarksText: {
      fontSize: "0.88rem",
      color: colors.grey[300],
      position: "relative",
      pl: "16px",
      "&::before": {
        content: '""',
        position: "absolute",
        left: 0,
        top: "8px",
        width: 6,
        height: 6,
        borderRadius: "50%",
        backgroundColor: colors.greenAccent[500],
      },
    },
    signalementCard: {
      backgroundColor: isDark ? "rgba(15, 23, 32, 0.6)" : "rgba(248, 250, 252, 0.8)",
      border: `1px solid ${border}`,
      borderRadius: "14px",
      p: "14px 18px",
    },
    signalementType: {
      fontSize: "0.86rem",
      fontWeight: 800,
      textTransform: "uppercase",
      letterSpacing: "0.04em",
    },
    signalementMeta: {
      fontSize: "0.8rem",
      color: colors.grey[400],
    },
    signalementComment: {
      flex: "1 1 280px",
      fontSize: "0.9rem",
      color: colors.grey[200],
      fontStyle: "italic",
    },
    alertColor: (type) => {
      const lower = (type || "").toLowerCase();
      if (lower.includes("dangereux") || lower.includes("grave")) return colors.redAccent[400];
      if (lower.includes("règle") || lower.includes("discipline")) return colors.greenAccent[400];
      if (lower.includes("physique")) return "#f59e0b";
      return colors.grey[200];
    },
    analyzedMiniChip: {
      backgroundColor: isDark ? "rgba(16, 185, 129, 0.15)" : "rgba(16, 185, 129, 0.1)",
      color: colors.greenAccent[400],
      height: 20,
      fontSize: "0.65rem",
      fontWeight: 800,
    },
    rowShell: {
      borderBottom: `1px solid ${border}`,
    },
    tableRow: {
      display: "flex",
      alignItems: "center",
      cursor: "pointer",
      px: { xs: "16px", md: "22px" },
      py: "16px",
      transition: "background-color 0.2s ease",
      "&:hover": {
        backgroundColor: isDark ? "rgba(30, 41, 59, 0.72)" : "rgba(241, 245, 249, 0.92)",
      },
    },
    avatarCell: {
      width: 60,
      flexShrink: 0,
    },
    avatarBadge: {
      width: 42,
      height: 42,
      borderRadius: "14px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "#f8fafc",
      fontWeight: 800,
      fontSize: "1rem",
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.22)",
    },
    nameCell: {
      flex: 1,
      minWidth: 0,
      pr: "16px",
    },
    studentName: {
      fontSize: "1rem",
      fontWeight: 800,
      color: colors.grey[100],
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    studentClass: {
      fontSize: "0.82rem",
      color: colors.grey[400],
    },
    metricCell: {
      width: 140,
      flexShrink: 0,
      display: { xs: "none", sm: "flex" },
      alignItems: "center",
    },
    countPill: (count) => ({
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      minWidth: 90,
      px: "12px",
      py: "6px",
      borderRadius: "999px",
      fontSize: "0.78rem",
      fontWeight: 700,
      color: count > 3 ? colors.redAccent[400] : colors.grey[200],
      backgroundColor: count > 3 ? (isDark ? "rgba(248, 113, 113, 0.12)" : "rgba(248, 113, 113, 0.08)") : mutedHeader,
      border: `1px solid ${count > 3 ? (isDark ? "rgba(248, 113, 113, 0.2)" : "rgba(248, 113, 113, 0.15)") : border}`,
    }),
    statusPendingChip: {
      backgroundColor: isDark ? "rgba(245, 158, 11, 0.15)" : "rgba(245, 158, 11, 0.1)",
      color: "#f59e0b",
      fontWeight: 700,
      border: `1px solid rgba(245, 158, 11, 0.25)`,
    },
    statusAnalyzedChip: {
      backgroundColor: isDark ? "rgba(16, 185, 129, 0.15)" : "rgba(16, 185, 129, 0.1)",
      color: colors.greenAccent[400],
      fontWeight: 700,
      border: `1px solid rgba(16, 185, 129, 0.25)`,
    },
    statusPartialChip: {
      backgroundColor: isDark ? "rgba(56, 189, 248, 0.15)" : "rgba(56, 189, 248, 0.1)",
      color: "#38bdf8",
      fontWeight: 700,
      border: `1px solid rgba(56, 189, 248, 0.25)`,
    },
    expandCell: {
      width: 40,
      display: "flex",
      justifyContent: "flex-end",
    },
    expandedRow: {
      p: { xs: "16px", md: "24px" },
      backgroundColor: isDark ? "rgba(10, 15, 23, 0.4)" : "rgba(248, 250, 252, 0.6)",
      borderTop: `1px solid ${border}`,
    },
    expandedTitle: {
      fontSize: "0.85rem",
      fontWeight: 800,
      color: colors.grey[400],
      textTransform: "uppercase",
      letterSpacing: "0.04em",
      mb: "16px",
    },
    panelShell: {
      borderRadius: "22px",
      background: surface,
      border: `1px solid ${border}`,
      boxShadow: isDark ? "0 18px 34px rgba(2, 6, 23, 0.32)" : "0 16px 34px rgba(148, 163, 184, 0.18)",
      overflow: "hidden",
    },
    panelHeader: {
      px: { xs: "16px", md: "22px" },
      py: { xs: "16px", md: "20px" },
      borderBottom: `1px solid ${border}`,
      display: "flex",
      justifyContent: "space-between",
      alignItems: { xs: "flex-start", sm: "center" },
      gap: "16px",
      flexDirection: { xs: "column", sm: "row" },
    },
    panelTitle: {
      fontSize: "1.08rem",
      fontWeight: 800,
      color: colors.grey[100],
    },
    panelSubtitle: {
      mt: "4px",
      fontSize: "0.86rem",
      color: colors.grey[400],
    },
    actionsRow: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      flexWrap: "wrap",
    },
    ghostActionButton: {
      color: colors.grey[300],
      fontSize: "0.82rem",
      fontWeight: 700,
      px: "14px",
      py: "8px",
      borderRadius: "12px",
      textTransform: "none",
      "&:hover": { backgroundColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.04)" },
    },
    secondaryActionButton: (aiEnabled) => ({
      color: aiEnabled ? colors.grey[100] : colors.grey[500],
      borderColor: aiEnabled ? border : isDark ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.08)",
      fontSize: "0.82rem",
      fontWeight: 700,
      px: "16px",
      py: "8px",
      borderRadius: "12px",
      textTransform: "none",
      "&:hover": {
        backgroundColor: aiEnabled ? (isDark ? "rgba(255,255,255,0.04)" : "rgba(0,0,0,0.02)") : "transparent",
        borderColor: aiEnabled ? colors.grey[400] : "inherit",
      },
      "&.Mui-disabled": {
        color: colors.grey[500],
        borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.08)",
      },
    }),
    primaryActionButton: (aiEnabled) => ({
      backgroundColor: aiEnabled ? colors.greenAccent[500] : mutedHeader,
      color: aiEnabled ? "#ffffff" : colors.grey[400],
      fontSize: "0.82rem",
      fontWeight: 800,
      px: "18px",
      py: "8px",
      borderRadius: "12px",
      textTransform: "none",
      boxShadow: aiEnabled ? `0 4px 12px ${colors.greenAccent[500]}40` : "none",
      "&:hover": {
        backgroundColor: aiEnabled ? colors.greenAccent[600] : mutedHeader,
      },
      "&.Mui-disabled": {
        backgroundColor: mutedHeader,
        color: colors.grey[500],
      },
    }),
    aiInlinePanel: {
      p: "20px 22px",
      backgroundColor: isDark ? "rgba(10, 15, 23, 0.4)" : "rgba(240, 246, 250, 0.5)",
      borderBottom: `1px solid ${border}`,
    },
    inlineAiIconWrap: {
      width: 38,
      height: 38,
      borderRadius: "10px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(45, 212, 191, 0.12)" : "rgba(13, 148, 136, 0.1)",
    },
    inlineAiTitle: {
      fontSize: "0.95rem",
      fontWeight: 800,
      color: colors.grey[100],
    },
    inlineAiText: {
      fontSize: "0.85rem",
      color: colors.grey[400],
      mt: "2px",
    },
    aiLoadingState: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "14px",
      py: "40px",
    },
    tableScroll: {
      overflowX: "auto",
    },
    tableInner: {
      minWidth: 600,
    },
    tableHeaderRow: {
      display: "flex",
      alignItems: "center",
      px: { xs: "16px", md: "22px" },
      py: "14px",
      backgroundColor: isDark ? "rgba(255,255,255,0.02)" : "rgba(0,0,0,0.02)",
      borderBottom: `1px solid ${border}`,
    },
    headerSpacerCell: {
      width: 60,
      flexShrink: 0,
    },
    headerNameCell: {
      flex: 1,
      minWidth: 0,
      pr: "16px",
    },
    headerText: {
      fontSize: "0.76rem",
      fontWeight: 800,
      color: colors.grey[400],
      textTransform: "uppercase",
      letterSpacing: "0.04em",
    },
    headerMetricCell: {
      width: 140,
      flexShrink: 0,
      display: { xs: "none", sm: "block" },
    },
    headerMetricCellLast: {
      width: 140,
      flexShrink: 0,
      display: { xs: "none", sm: "block" },
    },
    emptyState: {
      minHeight: 260,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "10px",
      px: "20px",
      textAlign: "center",
    },
    emptyStateIconWrap: {
      width: 52,
      height: 52,
      borderRadius: "18px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(45, 212, 191, 0.10)" : "rgba(13, 148, 136, 0.08)",
    },
    emptyStateTitle: {
      fontSize: "1rem",
      fontWeight: 800,
      color: colors.grey[100],
    },
    loadingState: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "14px",
      py: "80px",
    },
    loadingText: {
      fontSize: "0.9rem",
      color: colors.grey[400],
    },
    emptyPanel: {
      minHeight: 300,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "12px",
      backgroundColor: surface,
      borderRadius: "22px",
      border: `1px solid ${border}`,
      px: 3,
      textAlign: "center",
    },
  };
}
