export function getStyles(colors, isDark) {
  const surface = isDark ? "rgba(15, 23, 32, 0.88)" : "rgba(255, 255, 255, 0.82)";
  const surfaceAlt = isDark ? "rgba(19, 28, 39, 0.92)" : "#f8fafc";
  const border = isDark ? "rgba(148, 163, 184, 0.16)" : "rgba(148, 163, 184, 0.28)";

  return {
    toolbarShell: {
      mb: "18px",
      px: { xs: "14px", md: "18px" },
      py: { xs: "14px", md: "16px" },
      borderRadius: "18px",
      background: surface,
      border: `1px solid ${border}`,
      display: "flex",
      alignItems: { xs: "stretch", md: "center" },
      justifyContent: "space-between",
      gap: "14px",
      flexDirection: { xs: "column", md: "row" },
      boxShadow: isDark ? "0 16px 30px rgba(2, 6, 23, 0.24)" : "0 14px 28px rgba(148, 163, 184, 0.16)",
    },
    toolbarGroup: {
      display: "flex",
      alignItems: { xs: "stretch", sm: "center" },
      gap: "12px",
      flexDirection: { xs: "column", sm: "row" },
    },
    toolbarLabel: {
      fontSize: "0.82rem",
      fontWeight: 700,
      color: colors.grey[300],
      whiteSpace: "nowrap",
    },
    selectControl: {
      minWidth: 210,
      "& .MuiOutlinedInput-root": {
        borderRadius: "12px",
        backgroundColor: surfaceAlt,
      },
    },
    summaryGrid: {
      display: "grid",
      gridTemplateColumns: { xs: "1fr", md: "repeat(3, minmax(0, 1fr))" },
      gap: "16px",
      mb: "18px",
    },
    summaryCard: (color) => ({
      p: "22px 22px 24px",
      borderRadius: "20px",
      background: surface,
      border: `1px solid ${border}`,
      borderLeft: `4px solid ${color}`,
      boxShadow: isDark ? "0 18px 34px rgba(2, 6, 23, 0.28)" : "0 16px 32px rgba(148, 163, 184, 0.18)",
    }),
    summaryCardTopRow: {
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: "16px",
    },
    summaryLabel: {
      fontSize: "0.82rem",
      fontWeight: 700,
      color: colors.grey[400],
      textTransform: "uppercase",
      letterSpacing: "0.04em",
      mb: "10px",
    },
    summaryValue: {
      fontSize: { xs: "1.5rem", md: "1.7rem" },
      lineHeight: 1.1,
      fontWeight: 800,
      color: colors.grey[100],
    },
    summaryCurrency: {
      ml: 1,
      fontSize: "0.78rem",
      fontWeight: 700,
      color: colors.grey[400],
      letterSpacing: "0.04em",
      textTransform: "uppercase",
    },
    summaryIconWrap: (color) => ({
      width: 42,
      height: 42,
      borderRadius: "14px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(255,255,255,0.04)" : "rgba(15,23,42,0.04)",
      border: `1px solid ${isDark ? "rgba(255,255,255,0.06)" : "rgba(15,23,42,0.06)"}`,
      boxShadow: `inset 0 0 0 1px ${color}14`,
    }),
    summarySkeletonCard: {
      p: "22px 22px 24px",
      borderRadius: "20px",
      background: surface,
      border: `1px solid ${border}`,
    },
    chartsGrid: {
      display: "grid",
      gridTemplateColumns: { xs: "1fr", xl: "repeat(2, minmax(0, 1fr))" },
      gap: "18px",
      mb: "18px",
    },
    chartCard: {
      p: { xs: "18px", md: "22px" },
      borderRadius: "22px",
      background: surface,
      border: `1px solid ${border}`,
      boxShadow: isDark ? "0 18px 34px rgba(2, 6, 23, 0.28)" : "0 16px 32px rgba(148, 163, 184, 0.18)",
    },
    progressCard: {
      display: "flex",
      flexDirection: "column",
    },
    progressCardBody: {
      width: "100%",
      my: "auto",
    },
    sectionTitleRow: {
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: "12px",
      mb: "16px",
      flexWrap: "wrap",
    },
    sectionTitle: {
      fontSize: "1.08rem",
      fontWeight: 800,
      color: colors.grey[100],
    },
    sectionSubtitle: {
      mt: "4px",
      fontSize: "0.86rem",
      color: colors.grey[400],
    },
    metricBadgeWrap: {
      width: 38,
      height: 38,
      borderRadius: "14px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(45, 212, 191, 0.10)" : "rgba(13, 148, 136, 0.08)",
      border: `1px solid ${isDark ? "rgba(45, 212, 191, 0.16)" : "rgba(13, 148, 136, 0.14)"}`,
      flexShrink: 0,
    },
    progressTrack: {
      height: "22px",
      width: "100%",
      backgroundColor: isDark ? "rgba(255,255,255,0.04)" : "rgba(15,23,42,0.04)",
      borderRadius: "999px",
      mt: "18px",
      mb: "22px",
      display: "flex",
      overflow: "hidden",
      boxShadow: "inset 0 1px 3px rgba(0,0,0,0.1)",
    },
    progressPaid: (percent) => ({
      height: "100%",
      width: `${percent}%`,
      backgroundColor: "#17855d",
      transition: "width 0.8s cubic-bezier(0.4, 0, 0.2, 1)",
    }),
    progressPending: (percent, offset) => ({
      height: "100%",
      width: `${percent}%`,
      backgroundColor: "#e68472",
      borderLeft: percent > 0 && offset > 0 ? "2px solid rgba(255,255,255,0.15)" : "none",
      transition: "width 0.8s cubic-bezier(0.4, 0, 0.2, 1)",
    }),
    progressLegendRow: {
      display: "flex",
      alignItems: "center",
      gap: "24px",
      flexWrap: "wrap",
    },
    progressLegendItem: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    progressLegendDot: (color) => ({
      width: 10,
      height: 10,
      borderRadius: "999px",
      backgroundColor: color,
    }),
    progressLegendLabel: {
      fontSize: "0.82rem",
      fontWeight: 700,
      color: colors.grey[300],
    },
    progressLegendValue: {
      fontSize: "0.82rem",
      fontWeight: 800,
      color: colors.grey[100],
    },
    donutWrap: {
      position: "relative",
      height: 280,
      mt: "12px",
      width: "100%",
    },
    donutCenterLabel: {
      position: "absolute",
      top: "43%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      textAlign: "center",
      pointerEvents: "none",
    },
    donutCenterTitle: {
      fontSize: "0.74rem",
      fontWeight: 700,
      color: colors.grey[400],
      textTransform: "uppercase",
      letterSpacing: "0.05em",
      mb: "2px",
    },
    donutCenterValue: {
      fontSize: "1.4rem",
      lineHeight: 1.1,
      fontWeight: 800,
      color: colors.grey[100],
    },
    donutCenterCurrency: {
      fontSize: "0.7rem",
      fontWeight: 700,
      color: colors.grey[400],
      mt: "2px",
    },
    helperPill: {
      fontSize: "0.72rem",
      fontWeight: 700,
      color: colors.greenAccent[400],
      backgroundColor: isDark ? "rgba(45, 212, 191, 0.10)" : "rgba(13, 148, 136, 0.08)",
      px: "12px",
      py: "6px",
      borderRadius: "999px",
      border: `1px solid ${isDark ? "rgba(45, 212, 191, 0.16)" : "rgba(13, 148, 136, 0.14)"}`,
      mt: { xs: "8px", sm: 0 },
    },
    emptyChartState: {
      minHeight: 280,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      px: 3,
    },
    emptyChartTitle: {
      fontSize: "0.95rem",
      fontWeight: 700,
      color: colors.grey[200],
      mb: 1,
    },
    emptyChartText: {
      fontSize: "0.85rem",
      color: colors.grey[400],
      maxWidth: 320,
    },
    monthlyLegendRow: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "20px",
      pt: "4px",
    },
    monthlyLegendItem: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    monthlyLegendMarker: (color) => ({
      width: 10,
      height: 10,
      borderRadius: "999px",
      backgroundColor: color,
    }),
    monthlyLegendText: (color) => ({
      fontSize: "0.78rem",
      fontWeight: 700,
      color,
    }),
    statusChip: (color) => ({
      backgroundColor: `${color}14`,
      color: color,
      border: `1px solid ${color}36`,
      fontWeight: 700,
      borderRadius: "10px",
    }),
    modalPaper: {
      backgroundColor: isDark ? "#0f1720" : "#ffffff",
      backgroundImage: "none",
      borderRadius: "24px",
      border: `1px solid ${border}`,
      boxShadow: "0 24px 48px rgba(0,0,0,0.4)",
    },
    modalTitleRow: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      px: { xs: 2.5, md: 3 },
      pt: 3,
      pb: 2.5,
    },
    modalTitle: {
      fontSize: "1.2rem",
      fontWeight: 800,
      color: colors.grey[100],
    },
    modalSubtitle: {
      fontSize: "0.85rem",
      fontWeight: 600,
      color: colors.grey[400],
      textTransform: "capitalize",
      mt: 0.5,
    },
    modalCloseButton: {
      color: colors.grey[400],
      "&:hover": { color: colors.grey[100], backgroundColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.04)" },
    },
    modalTableWrap: {
      backgroundColor: isDark ? "rgba(30, 41, 59, 0.4)" : "#f8fafc",
      borderRadius: "16px",
      border: `1px solid ${border}`,
      overflow: "hidden",
    },
    modalTableRow: {
      "&:last-child td, &:last-child th": { border: 0 },
      "&:hover": { backgroundColor: isDark ? "rgba(255,255,255,0.02)" : "rgba(0,0,0,0.02)" },
    },
    headCell: {
      borderBottom: `1px solid ${border}`,
      color: colors.grey[400],
      fontWeight: 700,
      fontSize: "0.76rem",
      textTransform: "uppercase",
      letterSpacing: "0.04em",
      py: 1.5,
    },
    headCellLast: {
      borderBottom: `1px solid ${border}`,
      color: colors.grey[400],
      fontWeight: 700,
      fontSize: "0.76rem",
      textTransform: "uppercase",
      letterSpacing: "0.04em",
      py: 1.5,
      pr: 3,
    },
    bodyCell: {
      borderBottom: `1px solid ${border}`,
      color: colors.grey[200],
      fontSize: "0.85rem",
      py: 1.5,
    },
    amountCellExpected: {
      borderBottom: `1px solid ${border}`,
      color: colors.grey[400],
      fontSize: "0.85rem",
      fontWeight: 600,
      py: 1.5,
    },
    amountCellPaid: {
      borderBottom: `1px solid ${border}`,
      color: colors.grey[100],
      fontSize: "0.85rem",
      fontWeight: 800,
      py: 1.5,
      pr: 3,
    },
  };
}
